import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from '@/app/providers';
import Navbar from '@/components/layout/Navbar';
import LoginLayoutGate from '../components/layout/LoginLayoutGate';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`antialiased min-h-screen bg-[var(--color-bg)] text-[var(--color-text)]`}>
        <Providers>
          <LoginLayoutGate>
            {children}
          </LoginLayoutGate>
        </Providers>
      </body>
    </html>
  );
}
